swagger: "2.0"
info:
  version: "0.0.1"
  title: Shows API
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /:
    x-swagger-router-controller: shows
    post:
      description: Code challenge (Use Direct API as http://nine-code-challenge.herokuapp.com/)
      # used as the method name of the controller
      operationId: filter
      parameters:
        - name: payload
          in: body
          description: Shows json object
          required: true
          schema:
             $ref: "#/definitions/Payload"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ShowsFilterResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  ShowResponse:
    properties:
      image:
        type: string
      slug:
       type: string
      title:
       type: string
  Payload:
    type: object
    properties:
      payload:
        type: array
        items:
          $ref: "#/definitions/Show"
    required:
     - payload
  Show:
    type: object
    properties:
      country:
        type: [string, "null"]
        description: Country Code
      description:
        type: [string, "null"]
        description: description
      drm:
       type: [string, boolean,"null"]
       description: flag
      episodeCount:
       type: [integer, "null"]
       description: episode count
      genre:
        type: [string, "null"]
        description: category
      image:
       type: [object, "null"]
       properties: {
          showImage: {
            type: string
          }
       }
      language:
       type: [string, "null"]
       description: language
      nextEpisode:
       type: [object, "null"]
       description: next episode object 
      primaryColour:
       type: [string, "null"]
       description: colour 
      seasons: 
       type: [array, "null"]
       description: seasons object
      slug:
       type: string
       description: slug
      title:
       type: string
       description: title
      tvChannel:
       type: string
       description: tv channel
  ShowsFilterResponse:
    type: object
    properties:
      response:
        type: array
        items:
          $ref: "#/definitions/ShowResponse"
